version: "3.7"

services:
    # broker deployment
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        container_name: prosimos-rabbitmq
        # environment:
        #     - RABBITMQ_DEFAULT_USER=myuser
        #     - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            - 5672:5672 # port for the worker for tasks management
            - 15672:15672 # GUI port

    # worker deployment
    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        container_name: prosimos-celery-worker
        environment:
            - CELERY_BROKER_URL=amqp://rabbit:5672/
            - FLASK_DEBUG=1
        depends_on: 
        - rabbit

    # flask app deployment
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        container_name: prosimos-api
        ports:
            - 5000:5000
        environment:
            - CELERY_BROKER_URL=amqp://rabbit:5672/
            - FLASK_DEBUG=1