name: Dependencies check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SUBMODULE_PATH: ./external_tools/Prosimos

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        
    - name: Install submodule dependencies ${{ env.SUBMODULE_PATH }}
      run: |
        cd ${{ env.SUBMODULE_PATH }} && pip install -r requirements.txt
