name: Docker Image CI

on:
  create:
    
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

jobs:
  push_to_registry:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: [API] Extract metadata (tags, labels) for Docker
        id: api_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}
      
      - name: [API] Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ${{ steps.api_meta.outputs.tags }}

      - name: [CELERY] Extract metadata (tags, labels) for Docker 
        id: celery_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.DOCKER_NAMESPACE }}/${{ env.CELERY_DOCKER_REPOSITORY }}
      
      - name: [CELERY] Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile.worker
          push: true
          tags: ${{ steps.celery_meta.outputs.tags }}
